import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Card from "../components/Card";
import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
   return {
      props: {
         coffeeStores: coffeeStoresData,
      },
   };
}

export default function Home(props) {
   const handleOnClick = () => {};
   return (
      <div className={styles.container}>
         <Head>
            <title>Coffee Connnoisseur</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className={styles.main}>
            <Banner
               handleOnClick={handleOnClick}
               buttonText={"View stors nearby"}
            />
            <div className={styles.heroImage}>
               <Image
                  src="/static/undraw_coffee_with_friends_3cbj.svg"
                  width={650}
                  height={350}
               />
            </div>
            {props.coffeeStores.length > 0 && (
               <div className={styles.cartContainer}>
                  <h2 className={styles.heading2}>Toronto stores</h2>
                  <div className={styles.cardLayout}>
                     {props.coffeeStores.map((coffeeStore) => (
                        <Card
                           key={coffeeStore.id}
                           name={coffeeStore.name}
                           imgUrl={coffeeStore.imgUrl}
                           href={`/coffee-store/${coffeeStore.id}`}
                           className={styles.card}
                        />
                     ))}
                  </div>
               </div>
            )}
         </main>
      </div>
   );
}
